### PR TITLE
Update for eslint@>2.x

### LINKED ISSUE #10: space-after-keywords is deprecated since ESLint v2.0
It should be replaced with [keyword-spacing](http://eslint.org/docs/rules/keyword-spacing). I made [a fork with this change](https://github.com/robinvenneman/eslint-config-gulp), if it's ok I can make a PR.

### PR DESCRIPTION
**Pull request by BurtHarris**
Replace space-after-keywords with keyword-spacing
Adds eslint as a peer dependency

fixes #10

### CODE REVIEW

**Comment by phated** [comment]
I don't think we needs peerDeps

**Comment by BurtHarris** [comment]
You are probably right, I was thinking that would cause dependent projects to generate a warning if they are still using eslint@1, but testing it out that doesn't seem to work, at least with npm@3.10.10.

Update: No, I take that back.   I get the following message if the update isn't done in a dependency:

```
npm WARN eslint-config-gulp@2.1.0 requires a peer of eslint@^2.13.1 but none was installed.
```

That's what I was expecting.

**Comment by BurtHarris** [comment]
@phated I've removed the peer dependency.   Doesn't seem to hurt anything without it.

**Comment by pdehaan** [comment]
Yeah, peerDependencies were deprecated in npm@3 (per http://blog.npmjs.org/post/110924823920/npm-weekly-5)

**Comment by BurtHarris** [comment]
@pdehaan, I think peerDependencies had their behavior changed in npm@3, but not deprecated.   The behavior I expected is exactly what it says in that blog entry:

> We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies.

peerDependencies are in use in several well-maintained projects I've worked with, for example [__gulp-tsb__](https://www.npmjs.com/package/gulp-tsb) has a peerDependency on the TypeScript transpiler.   This way a warning is generated if TypeScript isn't also part of the same project that __gulp-tsb__ is.   But __gulp-tsb__ doesn't get it's own copy, it uses the version the containing project uses.

**Comment by BurtHarris** [comment]
Bump.   Blocking gulpjs/vinyl-fs#270

**Comment by phated** [comment]
Still considering this for eslint@2 support.  I'm going to take a look at this stuff with #8

**Review by gucong3000 — APPROVED** [review]

**Comment by phated** [comment]
I've opted for #15 - thanks though @BurtHarris

**Pull request closed without merging**
