### PR TITLE
Enforce object-curly-spacing rule

### PR DESCRIPTION
**Pull request by pdehaan**

### CODE REVIEW

**Comment by phated** [comment]
Do you think we should disable it or set it to "always"?

**Comment by pdehaan** [comment]
I'm fairly indifferent. At least setting it to `"always"` will force consistency. We could set it to "always" and then see how many other errors/warnings pop up in other repos.

**Comment by phated** [comment]
I think we should enforce it.  I used this same style for the 4.0 branch of the CLI, etc.

**Comment by pdehaan** [comment]
Pushed.

**Comment by phated** [comment]
Cool, will merge.  What semver bump makes sense?

**Comment by phated** [comment]
@pdehaan also, could you change the commit message? would hate to confuse people :stuck_out_tongue:

**Comment by pdehaan** [comment]
Done.

Re: version, we could bump to 2.0.0 since this will probably break a bunch of code throughout the repos.

**Comment by phated** [comment]
That's what I thought.  Published as 2.0.0

**Pull request merged**
